// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwpkzvzvyccazpqkhbor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3cGt6dnp2eWNjYXpwcWtoYm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTMyMTMsImV4cCI6MjA2MjEyOTIxM30.yBh7nyNgieDYnO7pRhi4F2Rl_BgwW8cbBXJh0e2OjwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);